### PR TITLE
chore(deps): bump dependencies

### LINKED ISSUE #132: Error install in Deno 1.14
eggs the great tool. but i'm try to install `deno install -Af --unstable https://x.nest.land/eggs@0.3.8/eggs.ts` and getting error :
```bash
error: TS2801 [ERROR]: This condition will always return true since this 'Promise<Deno.PermissionStatus>' is always defined.
  if (Deno.permissions.query({ name: "env" })) {
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/tty@0.1.2/is_interactive.ts:2:7

TS2773 [ERROR]:     Did you forget to use 'await'?
      if (Deno.permissions.query({ name: "env" })) {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/tty@0.1.2/is_interactive.ts:2:7
```

Deno: 1.14
eggs: 0.3.8

Thanks...

### PR DESCRIPTION
**Pull request by ebebbington**
Unable to use eggs latest on latest deno as some deps need to be updated

### CODE REVIEW

**Comment by ebebbington** [comment]
@oganexon really not sure why it's getting the error "unknown option -e", tried checking locally and the error is being thrown from cliffy/command/commands.ts, but there's no `-e` option in the eggs codebase

**Comment by maximousblk** [comment]
I'm not getting the "unknown option -e" but I am getting the "Too many arguments: eggs.ts 0.0.1-dev" error which is in the ci

not sure why but moving the `--check*` flags to the end doesn't cause the error

image

**Review by maximousblk — APPROVED** [review]

**Review by SteelAlloy — APPROVED** [review]
Thanks @ebebbington !

**Comment by ebebbington** [comment]
No problem, cheers for the approval :)

**Pull request merged**
