### PR TITLE
Can't link API key on Windows

### PR DESCRIPTION
**Pull request by moncefplastin07**
``HOMEPATH`` is not a currect dir path in windows .. because ``HOMEPATH`` in the environment variables in Windows returns  \Users\{usename} and this path is invalid for creating or reading the .nest-api-key file in Windows.

I get an error every time I try to create or link a .nest-api-key file via the command prompt and I also get a similar error when trying to deploy the module in nest.land via eggs for the same reason that. The nest-api-key file cannot be read even if you create it and manually put the API key in it

the error  : [CRIT] An unexpected error occurred: "The system cannot find the path specified. (os error 3)"
**
./eggs-debug.log
** file
```txt
Arguments:
  link,api-key

Deno version:
  deno: 1.4.1
  v8: 8.7.75
  typescript: 4.0.2

Eggs version:
  0.2.2

Platform:
  x86_64-pc-windows-msvc

2020-09-21T11:54:59.680Z [DEBUG]    Key:  "api-key"
2020-09-21T11:54:59.709Z [CRITICAL] An unexpected error occurred: "The system cannot find the path specified. (os error 3)" "NotFound: The system cannot find the path specified. (os error 3)\n    at Object.jsonOpAsync (core.js:236:13)\n    at async open (deno:cli/rt/30_files.js:44:17)\n    at async Object.writeFile (deno:cli/rt/40_write_file.js:54:18)\n    at async writeAPIKey (keyfile.ts:23:3)\n    at async Command.linkCommand [as fn] (link.ts:15:3)\n    at async Command.execute (command.ts:796:9)\n    at async Command.parse (command.ts:731:14)\n    at async Command.parse (command.ts:688:14)\n    at async mod.ts:51:23"
```

### CODE REVIEW

**Comment by t8** [comment]
Thanks so much for the PR! Sorry to hear that the CLI isn't working for you. 

Would @oganexon or @maximousblk be able to test this on Windows?

**Comment by SteelAlloy** [comment]
I encountered this bug in CI recently ;) 
But there's a few things to change in order to fix it 
I'll explain tonight

**Comment by moncefplastin07** [comment]
@t8 Thanks @oganexon Yes, I have fix the error. You can try it on your Windows computer

**Comment by SteelAlloy** [comment]
I never noticed this bug under Windows because I use git bash, that's why I did some tests:

**Windows (cmd / PowerShell) :**
```
HOME: undefined
HOMEPATH: \Users\oganexon
USERPROFILE: C:\Users\oganexon
```

**Windows (git bash) :**
```
HOME: C:\Users\oganexon
HOMEPATH: \Users\oganexon   
USERPROFILE: C:\Users\oganexon
```

**Linux (WSL) :**
```
HOME: /home/oganexon
HOMEPATH: undefined
USERPROFILE: undefined
```

Seems like `HOMEPATH` is useless here but I didn't test macOS.
Can someone run this on mac ?
```ts
console.log(`HOME: ${Deno.env.get("HOME")}`)
console.log(`HOMEPATH: ${Deno.env.get("HOMEPATH")}`)
console.log(`USERPROFILE: ${Deno.env.get("USERPROFILE")}`)
```

**Comment by moncefplastin07** [comment]
I think the result is similar to the Linux result

HOME: /path/to/user/profile
HOMEPATH: undefined
USERPROFILE: undefined

**Review by SteelAlloy — APPROVED** [review]
LGTM ! Thanks for this PR 🙂

(Tested on macOS)
```
HOME: /Users/oganexon
HOMEPATH: undefined
USERPROFILE: undefined
```

**Pull request merged**
