### PR TITLE
fix: typos in bug_report.md

### PR DESCRIPTION
**Pull request by aykxt**

### CODE REVIEW

**Comment by littledivy** [comment]
hacktoberfest?

**Comment by aykxt** [comment]
> hacktoberfest?

I think fixing typos doesn't count tho

**Comment by martonlederer** [comment]
They can't check for that so it would count. However, if you find typos, open an issue. Pull requests are for fixes/additions to the actual code

**Comment by aykxt** [comment]
> They can't check for that so it would count.

Ah well, then why not :) 

> However, if you find typos, open an issue. Pull requests are for fixes/additions to the actual code

Will do it when I find more typos!

**Comment by aykxt** [comment]
I saw the typos when trying to report an issue because I had a problem publishing a package. I later discovered that the package name "crypto" was causing the problem. Is that a reserved name? (I am using the same name on deno.land)

**Comment by martonlederer** [comment]
It is not a reserved name so it should work 🤔

**Comment by aykxt** [comment]
> It is not a reserved name so it should work 🤔

I've tried the names "crypt" and "crypto2" and both worked.
When I try the name crypto, I get the following error message:

```
[CRITICAL] An unexpected error occurred: "Something broke when publishing... " "Error: Something broke when publishing... \n    at Command.publishCommand [as fn] (publish.ts:351:11)\n    at async Command.execute (command.ts:796:9)\n    at async Command.parse (command.ts:731:14)\n    at async Command.parse (command.ts:688:14)\n    at async mod.ts:51:23
```

So, the behavior is not intended? Should I open a new issue for that?

**Review by littledivy — DISMISSED** [review]
Looks genuine, not a spam :+1:

**Comment by littledivy** [comment]
@aykxt `crypto` is a reserved name - https://github.com/nestdotland/x/blob/c94add3607c9fb7b45ac916d5f0776eb0fc0aeb1/src/utils/reservedNames.ts#L25

**Comment by SteelAlloy** [comment]
@aykxt Thank you for these corrections 👍 
Recently we wrote a specification on how to contribute but it is not yet on the master branch.
https://github.com/nestdotland/eggs/blob/dev/.github/CONTRIBUTING.md
You have to make a request to the `dev` branch 🙂 
Please merge the latest changes from dev into this branch or create another branch from `dev`.

**Pull request closed without merging**
