### PR TITLE
Add Drake — a task runner for Deno

### PR DESCRIPTION
**Pull request by SteelAlloy**
This will greatly enhance the development experience 🎉
All the useful commands for the eggs development are grouped in the Drakefile.ts file, the workflows rely on it too.

task|description
----|----
check-format |Format source files.
dev    |      Development tools. Should ideally be run before each commit.
dry-publish | Reports the details of what would have been published.
dry-ship   |  Reports the details of what would have been shipped.
format     |  Format source files.
link     |    Links the nest.land API key.
lint      |   Lint source files.
publish   |   Publishes eggs to the nest.land registry.
ship       |  Ship eggs to nest.land.
test     |    Run tests.

The `eggignore` file has been added back because it contains patterns that are not present in the `.gitignore` file.

### CODE REVIEW

**Review by t8 — COMMENTED** [review]
@oganexon has this been tested? Everything looks fine to me, but I wanted to check before merging.

**Comment by SteelAlloy** [comment]
@t8 yes, drake is used for everything in CI so it works 😉
However, I still have to change a couple of things, reference to what I wrote on discord
Sorry to be so volatile, I think about things during the day and implement them in the evening 😄

**Comment by t8** [comment]
No worries! Totally understand :)

**Comment by SteelAlloy** [comment]
@t8 In fact what I wanted to do is too ambitious. This PR is ready to be reviewed !

**Review by t8 — APPROVED** [review]
LGTM!

**Pull request merged**
