### PR TITLE
config

### LINKED ISSUE #68: Generate an error for files/folders that do not exist while publishing

### LINKED ISSUE #77: Getting "[ERR] No /mod.ts found in config. An entry file is required." when the entry file is not mod.ts.
**Describe the bug**

In eggs version 0.2.2, whatever I set the `entry` property to in the `egg.json` (or `egg.yaml`) file, I get the following error when running `eggs publish`: 
`[ERR] No /mod.ts found in config. An entry file is required.`
This happens whether there is an `entry` property; whether the the entry file mentioned exists; whether there is a  `./`, `/` or nothing preceding the file name; whether the file extention is `.js` or `.ts` ~~and whether the entry file is set to `mod.ts` or something else~~ _(actually I only get this problem when the entry file isn't `mod.ts`)_.

All the other properties seem to be working fine (I only get errors about not having a name, description or version if they aren't included in egg.json) but for some reason it never seems to pick up on the `entry` property.

 **To Reproduce**

I am using Windows 10, Deno 1.4.1, Eggs 0.2.2.  It seems to be happening with any eggs project.

### LINKED ISSUE #78: Running tests and formatting for publish command
Both a bug and a feature request.

**Is your feature request related to a problem? If so, please describe.**
1. I run `eggs publish`

2. Formatting the code takes a long time because it is formatting everything. Problem is i have node_modules and other files that are actually completely unrelated to what i'm publishing (this is problem 1)

3. When the publish command runs tests, it fails for me. Reason for this is because the command eggs uses to test, isn't what I use - eggs is running tests on files it shouldn't

I'm sure i won't only experience these problems - maybe other modules use `cd tests/some/dir && deno test`

**Describe the solution you'd like**
This is to propose a few things:

1. Only format files specified in the `egg.json`. I think this makes sense as i assume nest wants the. files formatted so when people check out the module on nest.land, it looks pretty - but they would only be seeing the files specified from `egg.json`

2. Allow a user to maybe customise the test command, or maybe a new field/property in `egg.json` that either specifies the directory or test command to run

3. Send to stdout **before** eggs starts formatting, because like i said, it took about a minute or more for me, so i was starting to assume the command was broken (problem 2), for. example, to. test my deno files, i. do `cd tests/deno && deno test -A`, whereas the `publish` command does `deno test -A --unstable`. I also believe. using the `--unstable` flag **should be optional**, because that command could break whenever, meaning modules that don't need it cant be published as the cli will error (possible problem 3)

**Describe alternatives you've considered**
None

**Additional context**
The repo i want to publish: https://github.com/ebebbington/context-finder

This repo is a project for both Node and Deno, hence the node_modules and other unrelated js code - there's a deno and node variant for everything, which is why it's problematic that the publish command runs `deno test` and `deno fmt` at the root directory

### PR DESCRIPTION
**Pull request by SteelAlloy**
- [x] (fix) `--entry` was set by default to `mod.ts` and was overwriting the `entry` field
- [x] (fix) add entry file to the list of uploaded files in any case
- [x] (fix) rewrite `ignore` field as `string[]` instead of `Ignore` object
- [x] (fix) format matched files by default
- [x] (fix) allow `--no-check-format`, `--no-check-tests`, `--no-check-installation` when `--check-all` is set to `true`
- [x] (feat) generate an error for files/folders that do not exist while publishing
- [x] (feat) allow for custom command in `--check-format`
- [x] (feat) allow for custom command in `--check-tests`
- [x] (feat) spinners while checks are performed
spinner

### CODE REVIEW

**Comment by SteelAlloy** [comment]
@t8 ready to be merged once reviewed 😉

**Review by t8 — APPROVED** [review]
LGTM

We may need to update the docs for this...

**Comment by t8** [comment]
Wait, nevermind. My apologies! I noticed the entry field going to optional in this PR and assumed incorrectly.

**Comment by SteelAlloy** [comment]
> 
> 
> LGTM
> 
> We may need to update the docs for this...

@t8 Don't worry, I'll write doc for this version as always 😀

**Pull request merged**
