### PR TITLE
feat: use yolk for publishing

### PR DESCRIPTION
**Pull request by littledivy**
**Publishing with a wallet** - 
image

To be merged when API is deployed.

### CODE REVIEW

**Review by t8 — DISMISSED** [review]
LGTM, but someone should definitely test this! I'd assume we want to wait to merge until MVP 2 is ready to be rolled out. 

Amazing work on integration, @divy-work, and amazing work on making it so easy to integrate with Yolk, @qu4k!

**Review by notfilippo — CHANGES_REQUESTED** [review]
LGTM, needs test and checks for lint should not fail. Great work @divy-work

**Review by SteelAlloy — DISMISSED** [review]
Awesome @divy-work! 
I was waiting for it to be finished so I could do the first step of the remote modules:
- Passing a majority of the fields in the egg.json file as options to the command 
- After that we can talk about how to do the remotes modules 👍

**Comment by littledivy** [comment]
> LGTM, needs test and checks for lint should not fail. Great work @divy-work

@qu4k Yup, the linter failed because of wrong yolk typings. Will fix it on yolk :smile: 

EDIT: Fixed

**Comment by notfilippo** [comment]
Linter happy - Filippo happy

**Review by notfilippo — DISMISSED** [review]
GGGG

**Review by t8 — DISMISSED** [review]
Yes yes yes

**Comment by t8** [comment]
Somebody should still test this more in-depth though. My test was very basic.

**Comment by littledivy** [comment]
@t8 agreed. I've done tests on a few test cases:

- Publish a brand new module - should (OK)
- Republish without upgrading the version - should (FAIL)
- Upgrade to another valid semver version - should (OK)
- Republish with a invalid semver version - should (FAIL)
- Set upload to false - should (OK)
- Pass a valid arweave wallet to the publish command - should (OK)

- Pass an invalid wallet - should (FAIL)

And a few load tests with `wrk`

**Comment by t8** [comment]
Oh, awesome. Great to hear!

**Review by SteelAlloy — DISMISSED** [review]
LGTM
Ready to be merged when API is deployed !

**Review by t8 — DISMISSED** [review]
LGTM!

**Comment by SteelAlloy** [comment]
Bruh there were still conflicts, the same ones

**Comment by SteelAlloy** [comment]
@divy-work this branch is now up to date with the dev branch.
I'll let you check if I have forgotten anything during the conflict resolution process.

`https://raw.github.com/nestdotland/yolk/x/mod.ts` no longer exists and `https://x.nest.land/yolk@0.1.0-rc4/mod.ts` does not seem to be up to date
image

**Comment by maximousblk** [comment]
closing this for now...

**Pull request closed without merging**
