### PR TITLE
Extract commands with scoped-only permissions (#8)

### PR DESCRIPTION
**Pull request by SteelAlloy**
Potential solution to #8

```sh
deno install --unstable --allow-read="./" --allow-write="./egg.json","./egg.yml","./egg.yaml" -n eggs-init https://x.nest.land/eggs@0.2.0/mod/init.ts
deno install --unstable --allow-read="./","[PATH_TO-HOME]\.nest-api-key" --allow-net="nest.land" --allow-env -n eggs-publish https://x.nest.land/eggs@0.2.0/mod/publish.ts
# and so on
```

Would you be okay with that? @jsejcksn

### CODE REVIEW

**Comment by jsejcksn** [comment]
@oganexon It's looking better! These permissions are still a bit too broad, though. I'm not trying to write a privacy manifesto here, but hear me out: the core idea is "no need of access = no possibility of access".

`--allow-env`

- This gives the app permission to read all environment variables (including private, unrelated ones). If there are certain values that are needed by the program, they should be able to be specified as [arguments to the script](https://deno.land/std/flags).

`--allow-read="./"`

- Your example doesn't clarify what is the CWD when executing those commands. (Should I assume it's `$HOME`?)

- This would need to be isolated to individual files chosen by the user, rather than an entire directory (like the write permission: `--allow-write="./egg.json","./egg.yml","./egg.yaml"`). I realize that this might mean a bit more work on your part to document which files need to be specified. The user can always specify an entire directory _if desired, but shouldn't be forced to_.

**Comment by SteelAlloy** [comment]
@jsejcksn made a few adjustments:
```sh
deno run --unstable --allow-read="./","[HOME-PATH-HERE]/.nest-api-key" --allow-net="nest.land" --allow-env="HOME","HOMEPATH","USERPROFILE" -n eggs-publish https://x.nest.land/eggs@0.2.0/mod/publish.ts
```

`--allow-env="HOME","HOMEPATH","USERPROFILE"` is required to find `\.nest-api-key`, so I added the corresponding variables

`--allow-read="./"` is required to read files in the CWD you executed the command, that is to say to upload module files to nest.land. If you want to be less permissive, just replace it with `--allow-read="./README.md","./mod.ts","[...]"`

`--allow-write="./egg.json","./egg.yml","./egg.yaml"` is needed in `eggs init` because we need to scan for config files if none is present.

Let me know if you have any more questions

**Comment by jsejcksn** [comment]
> `--allow-env="HOME","HOMEPATH","USERPROFILE"` is required to find `\.nest-api-key`, so I added the corresponding variables

`--allow-env` [does not support a list](https://deno.land/manual/getting_started/permissions#permissions-list). Right now it's all-or-nothing, so that's why I suggested accepting any required environment variable values as args.

There's discussion to provide granular env permissions (see https://github.com/denoland/deno/issues/3137, https://github.com/denoland/deno/issues/6683#issuecomment-655259075), and I'm hopeful for that functionality in the future.

> `--allow-write="./egg.json","./egg.yml","./egg.yaml"` is needed in `eggs init` because we need to scan for config files if none is present.

I don't understand what is meant by "we need to scan for". Can you explain? The `write` permission does not allow for reading. If they need to be checked for existence before being written, wouldn't they also need to be in the `--allow-read` permission list?

**Comment by martonlederer** [comment]
I understand your concerns about privacy and safety, but this is an open source project and it doesn't have that much code. You can just check the commands before using them in the repo

**Comment by jsejcksn** [comment]
@MartonDev It's not reasonable to ask for individuals to audit a cascade of dependencies on every release when there is a sandbox to do the job for them.

**Comment by martonlederer** [comment]
I'd agree, if this was a paid service, but everyone is working voluntarily

**Comment by jsejcksn** [comment]
@MartonDev I'm not sure how those are related. Are you implying that features are worth spending development time on but not privacy and security?

**Comment by martonlederer** [comment]
No, I replied this to your comment that we are "asking individuals to audit". But as I said, I understand your concerns, but you have to see, an average user will not care about security in that much detail. They know the project is open source and if someone is more sceptical, or cares more about security, like you, they can check the repo

**Comment by jsejcksn** [comment]
> an average user will not care about security in that much detail

That's a problem you can help fix instead of perpetuate.

Making it more difficult to be more secure is part of the reason why that happens.

**Comment by notfilippo** [comment]
Hi @jsejcksn , just checking in on the discussion.
 Our main priority for now with this CLI is to create a MVP that will be easy to use for the casual dev.  Once we get those feature stable we can start to think about integrating more security with the deno sandbox, maybe even not requiring any permission to run and just hooking up to the [Permissions api](https://deno.land/manual/examples/permissions) in the deno stdlib.  If you really need this feature at the moment I suggest you open a PR yourself, I will be happy to contribute.

**Comment by t8** [comment]
@jsejcksn For now, I'm going to close this PR. Don't get me wrong; we are HIGHLY focused on security and promoting trust between our platform and our users. 

> There's discussion to provide granular env permissions (see [denoland/deno#3137](https://github.com/denoland/deno/issues/3137), [denoland/deno#6683 (comment)](https://github.com/denoland/deno/issues/6683#issuecomment-655259075)), and I'm hopeful for that functionality in the future.

For us, we're very focused on adding additional features and improving the security in other areas of the service right now. Based on the comment above, this seems more of a Deno issue than a nest.land issue. I think that for now, the best thing to suit your needs will be [yolk](https://github.com/nestdotland/yolk). It's still in development and not functional because our Rust API isn't yet deployed, but this will allow you much more freedom when we get it off the ground. 

Because of the way our CLI functions, we're restricted to requiring certain permissions that I understand won't suit what you're looking for. Our CLI functions this way not to have free roam over a user and their machine, but instead to improve the user experience when publishing a module to our platform. I hope you can understand where I'm coming from, and I would be more than happy to personally reach out when yolk is ready for use!

I appreciate the interest you've taken in our platform thus far.

Tate

**Pull request closed without merging**
