### PR TITLE
0.2.2

### PR DESCRIPTION
**Pull request by SteelAlloy**

### CODE REVIEW

**Review by littledivy — DISMISSED** [review]

**Comment by SteelAlloy** [comment]
I have just noticed the drastic drop in performance due to the huge amount of dependencies from analyzer.
Do not publish eggs as long as this problem is present

**Comment by SteelAlloy** [comment]
Alright, the performance problem has been solved, version 0.2.2 can be released!

**Review by littledivy — DISMISSED** [review]

**Review by t8 — DISMISSED** [review]
LGTM

Are we merging #61 before this?

**Comment by SteelAlloy** [comment]
@t8 We haven't released for some time, some people are waiting for the bug `entry` to be fixed.
#61 still ~~requires some discussion~~ and the documentation is not ready, I think we can release it now 🙂

Anyway I can't decide this alone, we still have a workflow bug 😅
image

**Comment by notfilippo** [comment]
> Anyway I can't decide this alone, we still have a workflow bug 😅
> image

I've taken a look around, don't really know why this is happening... 🤷‍♂️

**Comment by SteelAlloy** [comment]
https://github.com/nestdotland/eggs/issues/71 needs to be addressed 

Edit: done

**Review by t8 — APPROVED** [review]
LGTM

**Review by martonlederer — APPROVED** [review]

**Pull request merged**
