### PR TITLE
"extends" keyword in .eggignore & pattern format

### LINKED ISSUE #66: extend .eggignore with a particular syntax
**Is your feature request related to a problem? If so, please describe.**
While working on a particular project, I almost published my keyfile to nest.land :fearful: 
I had forgot to setup my `.eggignore` like my `.gitignore`

**Describe the solution you'd like**
A new, easy to implement syntax for `.eggignore`

```sh
extends .gitignore

./other/files/to/ignore
```

**Describe alternatives you've considered**
Copy paste my gitignore to eggignore

### PR DESCRIPTION
**Pull request by SteelAlloy**
closes #66 

- New `extends` keyword to "import" other ignore files.

- Fix ignore pattern format
  - now matches perfectly with the `.gitignore` format.

In italics the previous functionalities, in bold the additions
https://git-scm.com/docs/gitignore#_pattern_format

 -   _A blank line matches no files, so it can serve as a separator for readability._

 -   _A line starting with # serves as a comment._ **Put a backslash ("\") in front of the first hash for patterns that begin with a hash.**

 -   **Trailing spaces are ignored unless they are quoted with backslash ("\")**.

 -   _An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined._ **Put a backslash ("\") in front of the first "!" for patterns that begin with a literal "!", for example, "\!important!.txt".**

 -   _The slash / is used as the directory separator. Separators may occur at the beginning, middle or end of the .gitignore search pattern._

 -   **If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.**

 -   **If there is a separator at the end of the pattern then the pattern will only match directories, otherwise the pattern can match both files and directories.**

 -   **For example, a pattern doc/frotz/ matches doc/frotz directory, but not a/doc/frotz directory; however frotz/ matches frotz and a/frotz that is a directory (all paths are relative from the .gitignore file).**

 -   _An asterisk "*" matches anything except a slash. The character "?" matches any one character except "/". The range notation, e.g. [a-zA-Z], can be used to match one of the characters in a range. See fnmatch(3) and the FNM_PATHNAME flag for a more detailed description._

 -   _Two consecutive asterisks ("*\*") in patterns matched against full pathname may have special meaning:_

 -   _A leading "*\*" followed by a slash means match in all directories. For example, "*\*/foo" matches file or directory "foo" anywhere, the same as pattern "foo". "**/foo/bar" matches file or directory "bar" anywhere that is directly under directory "foo"._

 -   _A trailing "/*\*" matches everything inside. For example, "abc/*\*" matches all files inside directory "abc", relative to the location of the .gitignore file, with infinite depth._

 -   _A slash followed by two consecutive asterisks then a slash matches zero or more directories. For example, "a/**/b" matches "a/b", "a/x/b", "a/x/y/b" and so on._

 -   _Other consecutive asterisks are considered regular asterisks and will match according to the previous rules._

### CODE REVIEW

**Review by t8 — DISMISSED** [review]
Assuming the updated `ignore_test` passes, LGTM!

**Comment by SteelAlloy** [comment]
Sorry I encountered several bugs, there is still work to be done. 😅

**Comment by t8** [comment]
No worries!

**Comment by SteelAlloy** [comment]
Everything works as planned, I didn't think I could do it but now absolutely all the rules of gitignore are operational!

**Review by t8 — APPROVED** [review]

**Pull request merged**
