### PR TITLE
Display the correspondig help of a sub-command after an error

### PR DESCRIPTION
**Pull request by SteelAlloy**
With the creation of the custom logger, when an error occurred the global help was displayed instead of the help for the sub-command. This is now fixed.

Before:
image

After:
image

### CODE REVIEW

**Review by notfilippo — COMMENTED** [review]
GJ

Edit: ups, I have to approve it

**Review by notfilippo — DISMISSED** [review]
👍🏻

**Review by t8 — DISMISSED** [review]
LGTM

Thanks for fixing this! I just removed that redundant linting check as well, so this should be good to merge.

**Comment by SteelAlloy** [comment]
Oops I copied the latest version of eggs-ci without looking at the changes, `ship.yml` should not be changed.

**Review by t8 — APPROVED** [review]
Oops, sorry for not noticing that! Thanks for fixing it.

**Pull request merged**
